### ISSUE TITLE
Use images from Application Documents Directory

### ISSUE THREAD

**Issue by piedcipher** [mdg-soc-19/explode-view#3]
Is it possible to use images from the `Application Documents Directory`? I tried but it didn't work. Could anyone please help? Thanks.

**Comment by hemilpanchiwala** [comment]
@piedcipher, I am not getting what are you meaning by `Application Documents Directory` as in explode-view, only the path of the image is required. Can you please explain your issue more detailed?

**Comment by piedcipher** [comment]
I'm using [path_provider](https://pub.dev/packages/path_provider) to store an image file in Application Documents Directory of my app.

I checked the source code of ExplodeView and I found that only assets (image assets) bundled with app can be used for ExplodeView.

**Comment by piedcipher** [comment]
May be I can help with implementation, I'm not sure but I can try it on my end.

**Comment by hemilpanchiwala** [comment]
> I checked the source code of ExplodeView and I found that only assets (image assets) bundled with app can be used for ExplodeView.

Yeah, currently explode_view only supports assets bundled with app only. It would be great if you can contribute to explode-view expanding its features. If you want to contribute, then just make the PR and I will review the code and send you the feedback (if necessary) and once it gets perfect we will add it in the repository.

**Comment by piedcipher** [comment]
Sounds good 👍

**Comment by piedcipher** [comment]
Hey, I tried running the example app and the effect isn't working for me. I used an emulator and a real device both. But didn't work in either of them.
![Screenshot at 2020-10-02 23-21-40](https://user-images.githubusercontent.com/13456345/94954089-3316b180-0506-11eb-9bd7-4f3f883400f3.png)

**Comment by hemilpanchiwala** [comment]
@piedcipher, have you long-pressed on the images as it will break into particles only after that?

**Comment by piedcipher** [comment]
Oh! Let me try that.

**Comment by piedcipher** [comment]
That worked! Thanks. It should be mentioned somewhere top in readme file.

**Comment by piedcipher** [comment]
I think I've gotten it working. I'm thinking about passing ByteData in ExplodeView. Should we discuss it here? or should I create a draft PR and continue the discussion there?
